name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - uses: gradle/actions/wrapper-validation@v3
      - name: Build with Gradle
        run: ./gradlew check assemble
